### PR TITLE
hotfix/rig-monitor-multiple

### PR DESCRIPTION
**Pull request by wishbone1138**
Multiple fixes:

rig-monitor: We were only writing out the last binary data in the rig_list, not each one.  I've put the write out in the loop and it works, but we could collect all rig data first to a tmp dir and then write out to db afterword if you prefer, might be more efficient long term?

miners - added miner tag to miner_gpu measurement.  I think it needs to be here if we're removing the [module] name from the measurement?

miner-ewbf - removed my integer "i" options from the database writes.  If we're removing the [module] in the measurement then all of our definitions must match up or it will error on the write.  I had to fix a couple of mismatches here.  Haven't tested extensively and I don't have sgminer at the moment, so we'll need that tested.

### CODE REVIEW

**Comment by rodneymo** [comment]
>rig-monitor: We were only writing out the last binary data in the rig_list, not each one. I've put the write out in the loop and it works, but we could collect all rig data first to a tmp dir and then write out to db afterword if you prefer, might be more efficient long term?

That's weird. I thought I had fixed that as I pushed all the binary_data to a tmp file ahead of calling curl. Maybe I only did if for pool-monitor. I'll check. 
I think having a single write per master monitor is the way to go for performance

**Comment by rodneymo** [comment]
Indeed. Single write is pool and plug master is support, but not on all miner scrips (claymore and ewbf). We need to replace the 
BINARY_DATA assignment with 
LINE=...
DATA_BINARY="${DATA_BINARY}"$'\n'"${LINE}"

**Comment by wishbone1138** [comment]
gotcha, I figured that's what you might be going for.

**Comment by rodneymo** [comment]
Fixed in claymore and ewbf. Updated rig-monitor too.

**Pull request merged**
